name: GROW
favicon: null
layout_spectrum: 0.9161148970015347
typography_spectrum: 0.4488760414533317
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.33843821566551924
  lightness: 0.9205197058618069
  saturation: 0.014028043486177921
  rhythmicContrast: 0.08482736675068736
purpose: []
