name: GROW
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#554e3a'
    - '#20b500'
    - '#7ed56b'
    - '#c9efbe'
    - '#9d998d'
  brandStrength: 1
  lightness: 0.9205197058618069
  saturation: 0.014028043486177921
  rhythmicContrast: 0.08482736675068736
purpose: []
